/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        page: 'var(--color-page)',
        sidebar: 'var(--color-sidebar)',
        'sidebar-list': 'var(--color-sidebar-list)',
        'section-header': 'var(--color-section-header)',
        'sidebar-border': 'var(--color-sidebar-border)',
        card: 'var(--color-card)',
        primary: 'var(--color-text)',
        muted: 'var(--color-text-muted)',
        'text-inverse': 'var(--color-text-inverse)',
        border: 'var(--color-border)',
        'border-light': 'var(--color-border-light)',
        accent: 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',
        'accent-subtle': 'var(--color-accent-subtle)',
        'accent-subtle-text': 'var(--color-accent-subtle-text)',
        'list-hover': 'var(--color-list-hover)',
        'list-hover-text': 'var(--color-list-hover-text)',
        'nav-selected-bg': 'var(--color-nav-selected-bg)',
        'nav-selected-text': 'var(--color-nav-selected-text)',
        'nav-text': 'var(--color-nav-text)',
        'nav-hover-bg': 'var(--color-nav-hover-bg)',
        'user-bubble': 'var(--color-user-bubble)',
        'assistant-bubble': 'var(--color-assistant-bubble)',
        'assistant-border': 'var(--color-assistant-border)',
        'input-bg': 'var(--color-input-bg)',
        'input-border': 'var(--color-input-border)',
        'input-focus-ring': 'var(--color-input-focus-ring)',
        danger: 'var(--color-danger)',
        'danger-subtle': 'var(--color-danger-subtle)',
        'tool-call-border': 'var(--color-tool-call-border)',
        'tool-call-bg': 'var(--color-tool-call-bg)',
        'tool-call-text': 'var(--color-tool-call-text)',
        skill: 'var(--color-skill)',
        'loading-dot': 'var(--color-loading-dot)',
        placeholder: 'var(--color-placeholder)',
      },
    },
  },
  plugins: [],
}
