#!/usr/bin/env bash
set -euo pipefail

# Generate 1Panel "compose backup" tarball that contains compose_meta.json.
# Optional: pass an ST49 image tag to build/push ST49 image before packaging.
# Usage:
#   bash pack_1panel_backup.sh                 # only generate backup tarball
#   bash pack_1panel_backup.sh 26.05.12.5      # docker build + push, then package
# Output: <repo_root>/1panel-compose-backup.tar.gz

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Prefer git to locate repo root (works regardless of script location).
if command -v git >/dev/null 2>&1; then
  REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null || true)"
else
  REPO_ROOT=""
fi

# Fallbacks:
# - if script is in <repo>/scripts/, use parent
# - if script is in <repo>/, use itself
if [[ -z "${REPO_ROOT:-}" ]]; then
  if [[ "$(basename "$SCRIPT_DIR")" == "scripts" ]]; then
    REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
  else
    REPO_ROOT="$SCRIPT_DIR"
  fi
fi
cd "$REPO_ROOT"

IMAGE_TAG="${1:-}"
if [[ $# -gt 1 ]]; then
  echo "ERROR: too many arguments" >&2
  echo "Usage: bash $(basename "$0") [image_tag]" >&2
  exit 2
fi

ST49_VERSION="${ST49_VERSION:-26.05.12.5}"
SANDBOX_VERSION="${SANDBOX_VERSION:-26.05.12.1}"
IMAGE_REPO="${IMAGE_REPO:-crpi-hzqv5l81v3ftz5jl.cn-beijing.personal.cr.aliyuncs.com/free4inno-yuanfang2025/dha}"
SANDBOX_IMAGE_REPO="${SANDBOX_IMAGE_REPO:-crpi-hzqv5l81v3ftz5jl.cn-beijing.personal.cr.aliyuncs.com/free4inno-yuanfang2025/sandbox}"
ST49_IMAGE="${ST49_IMAGE:-${IMAGE_REPO}:${IMAGE_TAG:-$ST49_VERSION}}"
SANDBOX_STANDARD_IMAGE="${SANDBOX_STANDARD_IMAGE:-${SANDBOX_IMAGE_REPO}:${SANDBOX_VERSION}-standard}"
SANDBOX_PLAYWRIGHT_IMAGE="${SANDBOX_PLAYWRIGHT_IMAGE:-${SANDBOX_IMAGE_REPO}:${SANDBOX_VERSION}-playwright}"
IMAGE=""
if [[ -n "$IMAGE_TAG" ]]; then
  if [[ "$IMAGE_TAG" == *":"* || "$IMAGE_TAG" == *"/"* ]]; then
    echo "ERROR: image_tag should be a tag only, for example: 26.04.27" >&2
    exit 2
  fi
  IMAGE="$ST49_IMAGE"
  echo "==> Building image: $IMAGE"
  docker build --platform linux/amd64 -t "$IMAGE" .
  echo "==> Pushing image: $IMAGE"
  docker push "$IMAGE"
fi

OUT_TGZ="${OUT_TGZ:-1panel-compose-backup.tar.gz}"
COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.1panel.yml}"
ENV_FILE="${ENV_FILE:-backend/.env}"
COMPOSE_NAME="${COMPOSE_NAME:-st49}"

if [[ ! -f "$COMPOSE_FILE" ]]; then
  echo "ERROR: missing compose file: $COMPOSE_FILE" >&2
  exit 2
fi

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: missing env file: $ENV_FILE" >&2
  echo "Hint: copy backend/.env.1panel.example to backend/.env and fill keys." >&2
  exit 2
fi

WORK_DIR=".1panel-backup-src"
BACKUP_DIR="$WORK_DIR/1panel-compose-backup"
FILES_DIR="$BACKUP_DIR/compose_files"

rm -rf "$WORK_DIR"
mkdir -p "$FILES_DIR"

cp "$COMPOSE_FILE" "$FILES_DIR/00_docker-compose.yml"
cp "$ENV_FILE" "$FILES_DIR/.env"
{
  echo ""
  echo "# Generated by $(basename "$0") for 1Panel compose interpolation"
  echo "ST49_VERSION=$ST49_VERSION"
  echo "SANDBOX_VERSION=$SANDBOX_VERSION"
  echo "ST49_IMAGE=$ST49_IMAGE"
  echo "SANDBOX_BASE_IMAGE=$SANDBOX_STANDARD_IMAGE"
  echo "SANDBOX_STANDARD_IMAGE=$SANDBOX_STANDARD_IMAGE"
  echo "SANDBOX_PLAYWRIGHT_IMAGE=$SANDBOX_PLAYWRIGHT_IMAGE"
  echo "QWEN_AUDIO_CHUNK_SECONDS=${QWEN_AUDIO_CHUNK_SECONDS:-120}"
} >> "$FILES_DIR/.env"

python3 - <<'PY'
import json, pathlib, datetime, os
base = pathlib.Path(".1panel-backup-src/1panel-compose-backup")
compose_name = os.environ.get("COMPOSE_NAME", "st49")
meta = {
  "composeName": compose_name,
  "composePath": "",
  "createdAt": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
  "files": [
    {
      "originalPath": os.environ.get("COMPOSE_FILE", "docker-compose.1panel.yml"),
      "fileName": "docker-compose.yml",
      "relativePath": "docker-compose.yml",
      "backupPath": "compose_files/00_docker-compose.yml",
    }
  ],
  "containers": []
}
(base / "compose_meta.json").write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
PY

tar -czf "$OUT_TGZ" -C "$WORK_DIR" 1panel-compose-backup

echo "OK: wrote $OUT_TGZ"
echo "ST49_IMAGE: $ST49_IMAGE"
echo "SANDBOX_STANDARD_IMAGE: $SANDBOX_STANDARD_IMAGE"
echo "SANDBOX_PLAYWRIGHT_IMAGE: $SANDBOX_PLAYWRIGHT_IMAGE"
echo "Contents:"
tar -tzf "$OUT_TGZ"
echo ""
echo "Note: compose 内 st49 依赖 OpenSandbox healthcheck；若改了 backend 里网关/沙箱逻辑，需构建并更新 ST49_IMAGE 后远端才生效。"
