"""Command builders for installing user sandbox requirements."""
from __future__ import annotations

import base64
import shlex
from typing import Any

from app.agent.sandbox_policy_runtime import sandbox_default_environment


def requirements_text_b64(normalized_requirements: str) -> str:
    normalized = (normalized_requirements or "").strip()
    if not normalized:
        return ""
    return base64.b64encode(normalized.encode("utf-8")).decode("ascii")


def build_requirements_install_command(normalized_requirements: str) -> list[str]:
    b64 = requirements_text_b64(normalized_requirements)
    quoted_b64 = shlex.quote(b64)
    return [
        "sh",
        "-lc",
        (
            f"set -eux; SANDBOX_REQUIREMENTS_B64={quoted_b64}; export SANDBOX_REQUIREMENTS_B64; "
            "echo '=== sandbox requirements diagnostics ==='; "
            "echo python3_path=$(command -v python3 || true); "
            "python3 -V; "
            "python3 -m pip --version; "
            'REQ_B64="${SANDBOX_REQUIREMENTS_B64:-}"; '
            'python3 - <<\'PY\'\n'
            "import base64,os,sys\n"
            "b=os.environ.get('SANDBOX_REQUIREMENTS_B64','')\n"
            "data=base64.b64decode(b.encode('ascii')) if b else b''\n"
            "open('/tmp/requirements.txt','wb').write(data)\n"
            "print('wrote_requirements_bytes', len(data))\n"
            "if not data.strip():\n"
            "    raise SystemExit('requirements install received empty requirements payload')\n"
            "print('requirements_preview_start')\n"
            "for line in data.decode('utf-8', 'replace').splitlines():\n"
            "    text=line.strip()\n"
            "    if text and not text.startswith('#'):\n"
            "        print(text)\n"
            "print('requirements_preview_end')\n"
            "PY\n"
            "rm -f /tmp/requirements.preinstalled\n"
            "python3 - <<'PY'\n"
            "import importlib, importlib.metadata as md, re\n"
            "from pathlib import Path\n"
            "from packaging.requirements import InvalidRequirement, Requirement\n"
            "from packaging.version import InvalidVersion, Version\n"
            "print('requirements_precheck_start')\n"
            "import_names={'xlrd':['xlrd'], 'openpyxl':['openpyxl'], 'pandas':['pandas']}\n"
            "min_versions={'xlrd':'2.0.1'}\n"
            "missing=[]\n"
            "version_too_low=[]\n"
            "version_mismatch=[]\n"
            "import_missing=[]\n"
            "seen=[]\n"
            "for raw in open('/tmp/requirements.txt', encoding='utf-8'):\n"
            "    line=raw.strip()\n"
            "    if not line or line.startswith('#') or line.startswith(('-', '--')) or '://' in line or line.startswith(('git+', 'http:')):\n"
            "        continue\n"
            "    try:\n"
            "        req=Requirement(line)\n"
            "        name=req.name\n"
            "        specifier=req.specifier\n"
            "    except InvalidRequirement:\n"
            "        name=line.split(';',1)[0].split('[',1)[0].strip()\n"
            "        name=re.split(r'===|==|>=|<=|~=|!=|>|<', name, 1)[0].strip()\n"
            "        specifier=None\n"
            "    if not name:\n"
            "        continue\n"
            "    try:\n"
            "        version=md.version(name)\n"
            "        seen.append(f'{name}=={version}')\n"
            "        if specifier:\n"
            "            try:\n"
            "                if Version(version) not in specifier:\n"
            "                    version_mismatch.append(f'{name}=={version} not in {specifier}')\n"
            "            except InvalidVersion:\n"
            "                version_mismatch.append(f'{name}=={version} invalid version for {specifier}')\n"
            "        minimum=min_versions.get(name.lower())\n"
            "        if minimum and Version(version) < Version(minimum):\n"
            "            version_too_low.append(f'{name}=={version} < {minimum}')\n"
            "        for mod in import_names.get(name.lower(), []):\n"
            "            try:\n"
            "                importlib.import_module(mod)\n"
            "            except Exception as exc:\n"
            "                import_missing.append(f'{mod}: {exc}')\n"
            "    except md.PackageNotFoundError:\n"
            "        missing.append(name)\n"
            "for item in seen:\n"
            "    print(item)\n"
            "print('requirements_precheck_end')\n"
            "if not missing and not version_too_low and not version_mismatch and not import_missing:\n"
            "    Path('/tmp/requirements.preinstalled').write_text('1', encoding='utf-8')\n"
            "    print('requirements_precheck_satisfied')\n"
            "else:\n"
            "    if missing:\n"
            "        print('requirements_precheck_missing:' + ', '.join(missing))\n"
            "    if version_too_low:\n"
            "        print('requirements_precheck_version_too_low:' + '; '.join(version_too_low))\n"
            "    if version_mismatch:\n"
            "        print('requirements_precheck_version_mismatch:' + '; '.join(version_mismatch))\n"
            "    if import_missing:\n"
            "        print('requirements_precheck_import_missing:' + '; '.join(import_missing))\n"
            "PY\n"
            "if [ -f /tmp/requirements.preinstalled ]; then\n"
            "  echo 'requirements_install_skip reason=already_satisfied';\n"
            "else\n"
            "  python3 -m pip install --disable-pip-version-check --no-input -r /tmp/requirements.txt;\n"
            "fi\n"
            "python3 - <<'PY'\n"
            "import importlib, importlib.metadata as md\n"
            "from packaging.requirements import InvalidRequirement, Requirement\n"
            "from packaging.version import InvalidVersion, Version\n"
            "import re\n"
            "print('requirements_verify_start')\n"
            "missing=[]\n"
            "import_missing=[]\n"
            "version_too_low=[]\n"
            "version_mismatch=[]\n"
            "seen=[]\n"
            "import_names={'xlrd':['xlrd'], 'openpyxl':['openpyxl'], 'pandas':['pandas']}\n"
            "min_versions={'xlrd':'2.0.1'}\n"
            "for raw in open('/tmp/requirements.txt', encoding='utf-8'):\n"
            "    line=raw.strip()\n"
            "    if not line or line.startswith('#') or line.startswith(('-', '--')) or '://' in line or line.startswith(('git+', 'http:')):\n"
            "        continue\n"
            "    try:\n"
            "        req=Requirement(line)\n"
            "        name=req.name\n"
            "        specifier=req.specifier\n"
            "    except InvalidRequirement:\n"
            "        name=line.split(';',1)[0].split('[',1)[0].strip()\n"
            "        name=re.split(r'===|==|>=|<=|~=|!=|>|<', name, 1)[0].strip()\n"
            "        specifier=None\n"
            "    if not name:\n"
            "        continue\n"
            "    try:\n"
            "        version=md.version(name)\n"
            "        seen.append(f'{name}=={version}')\n"
            "        if specifier:\n"
            "            try:\n"
            "                if Version(version) not in specifier:\n"
            "                    version_mismatch.append(f'{name}=={version} not in {specifier}')\n"
            "            except InvalidVersion:\n"
            "                version_mismatch.append(f'{name}=={version} invalid version for {specifier}')\n"
            "        minimum=min_versions.get(name.lower())\n"
            "        if minimum and Version(version) < Version(minimum):\n"
            "            version_too_low.append(f'{name}=={version} < {minimum}')\n"
            "        for mod in import_names.get(name.lower(), []):\n"
            "            try:\n"
            "                importlib.import_module(mod)\n"
            "                print(f'import_ok:{mod}')\n"
            "            except Exception as exc:\n"
            "                import_missing.append(f'{mod}: {exc}')\n"
            "    except md.PackageNotFoundError:\n"
            "        missing.append(name)\n"
            "for item in seen:\n"
            "    print(item)\n"
            "print('requirements_verify_end')\n"
            "if missing:\n"
            "    raise SystemExit('missing packages after pip install: ' + ', '.join(missing))\n"
            "if version_too_low:\n"
            "    raise SystemExit('packages installed but version too low: ' + '; '.join(version_too_low))\n"
            "if version_mismatch:\n"
            "    raise SystemExit('packages installed but specifier mismatch: ' + '; '.join(version_mismatch))\n"
            "if import_missing:\n"
            "    raise SystemExit('packages installed but import failed: ' + '; '.join(import_missing))\n"
            "PY\n"
            "if [ \"${SANDBOX_AUTO_INSTALL_BROWSERS:-0}\" = \"1\" ] && grep -Eiq '^(playwright|patchright)([<=> ]|$)' /tmp/requirements.txt; then\n"
            "  echo 'browser_install_start variant='\"${SANDBOX_IMAGE_VARIANT:-}\";\n"
            "  if python3 -m patchright --help >/dev/null 2>&1; then\n"
            "    python3 -m patchright install chromium || python3 -m playwright install chromium\n"
            "  else\n"
            "    python3 -m playwright install chromium\n"
            "  fi\n"
            "  echo 'browser_install_done'\n"
            "fi"
        ),
    ]


def build_requirements_install_env(
    normalized_requirements: str,
    policy_environment: dict[str, Any] | None,
) -> dict[str, str]:
    return {
        **sandbox_default_environment(),
        **{str(k): str(v) for k, v in dict(policy_environment or {}).items() if v is not None},
        "SANDBOX_REQUIREMENTS_B64": requirements_text_b64(normalized_requirements),
    }
